sudo: required

services:
  - docker

before_install:
  - docker pull akshaychalana/dockerfiles

after_success:
  - ./upload-csv.sh

script:
  - docker run -v ~/data:/data akshaychalana/dockerfiles /bin/sh -c "apt remove -y python-pip;python3 -m pip install pytest tabulate;export CSVDIR='/data';python3 -m pytest pytorch/caffe2/python/onnx/tests/onnx_backend_test.py;"
