sudo: required

services:
  - docker

before_install:
  - docker pull akshaychalana/dockerfiles

after_success:
  - ./upload-csv.sh

script:
  - docker run -v ~/data:/data akshaychalana/dockerfiles /bin/sh -c "python check_date.py `docker inspect -f '{{ .Created }}' akshaychalana/dockerfiles`; apt remove -y python-pip; pip install pytest tabulate;export CSVDIR='/data'; pytest pytorch/caffe2/python/onnx/tests/onnx_backend_test.py;"
